version: '3'
services:
  howard:
    build: .
    ports:
      - 9010:9000
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:9000
      LH_ADDRESS: http://howard:9000
      LH_PEERS: http://winslow:9000,http://wake:9000

  wake:
    build: .
    ports:
      - 9011:9000
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:9000
      LH_ADDRESS: http://wake:9000
      LH_PEERS: http://winslow:9000,http://howard:9000

  winslow:
    build: .
    ports:
      - 9012:9000
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:9000
      LH_ADDRESS: http://winslow:9000
      LH_PEERS: http://howard:9000,http://wake:9000
