name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install Sonar Scanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Install dependencies
      run: dotnet restore
    - name: Begin Sonar Scanner
      run: dotnet sonarscanner begin /key:ahoka_Lighthouse /version:${GITHUB_SHA} /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=${SONAR_TOKEN}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: End Sonar Scanner
      run: dotnet sonarscanner end /d:sonar.login=${SONAR_TOKEN}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
